import { Achievement } from './types';

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_blood',
    title: 'First Blood',
    description: 'Destroy your first enemy ship.',
    unlocked: false,
    icon: 'Target'
  },
  {
    id: 'survivor',
    title: 'Survivor',
    description: 'Reach Level 5.',
    unlocked: false,
    icon: 'Heart'
  },
  {
    id: 'ace_pilot',
    title: 'Ace Pilot',
    description: 'Score 10,000 points.',
    unlocked: false,
    icon: 'Trophy'
  },
  {
    id: 'power_hungry',
    title: 'Power Hungry',
    description: 'Collect 5 power-ups in a single run.',
    unlocked: false,
    icon: 'Zap'
  },
  {
    id: 'untouchable',
    title: 'Untouchable',
    description: 'Destroy 50 enemies without losing a life.',
    unlocked: false,
    icon: 'Shield'
  }
];

export const TRANSLATIONS = {
  en: {
    title: "KING'S STAR WAR 2",
    subtitle: "The galaxy needs a hero",
    startMission: "INITIALIZE MISSION",
    missionPaused: "MISSION PAUSED",
    resume: "RESUME",
    abort: "ABORT MISSION",
    missionFailed: "MISSION FAILED",
    shipDestroyed: "Your ship was destroyed",
    finalScore: "Final Score",
    levelReached: "Level Reached",
    enemiesSlain: "Enemies Slain",
    achievements: "ACHIEVEMENTS",
    tryAgain: "TRY AGAIN",
    mainMenu: "MAIN MENU",
    missionIntel: "MISSION INTEL",
    enemyClasses: "Enemy Classes",
    tacticalInfo: "Tactical Info",
    striker: "STRIKER",
    strikerDesc: "Standard scout ship",
    interceptor: "INTERCEPTOR",
    interceptorDesc: "High speed, low HP",
    dreadnought: "DREADNOUGHT",
    dreadnoughtDesc: "Heavy armor, high HP",
    tactical1: "Escaping enemies will reduce your score by 50 points.",
    tactical2: "Level up clears all enemies from the sector.",
    tactical3: "Shields absorb one collision impact.",
    tactical4: "Triple shot lasts for 10 seconds.",
    controls: "CONTROLS",
    powerups: "POWER-UPS",
    move: "Move",
    shoot: "Shoot",
    pause: "Pause",
    mobile: "Mobile",
    tripleShot: "TRIPLE SHOT",
    shield: "SHIELD",
    highScore: "High Score",
    level: "Level",
    achievementUnlocked: "Achievement Unlocked!",
    gameplayIntro: "Pilot your starfighter through enemy territory. Destroy incoming threats, collect power-ups, and survive as long as possible to achieve the highest score.",
    howToPlay: "HOW TO PLAY",
    achievementList: "ACHIEVEMENT CHALLENGES",
    tripleShotDesc: "Fires 3 bullets at once",
    shieldDesc: "Protects from one hit",
    repair: "REPAIR",
    repairDesc: "Restores 1 life (Max 3)",
    powerupClasses: "Power-up Types",
    achievements_data: {
      first_blood: { title: "First Blood", desc: "Destroy your first enemy ship." },
      survivor: { title: "Survivor", desc: "Reach Level 5." },
      ace_pilot: { title: "Ace Pilot", desc: "Score 10,000 points." },
      power_hungry: { title: "Power Hungry", desc: "Collect 5 power-ups in a single run." },
      untouchable: { title: "Untouchable", desc: "Destroy 50 enemies without losing a life." }
    }
  },
  zh: {
    title: "King的星际战争 2",
    subtitle: "银河系需要英雄",
    startMission: "初始化任务",
    missionPaused: "任务暂停",
    resume: "继续游戏",
    abort: "中止任务",
    missionFailed: "任务失败",
    shipDestroyed: "你的战机已被摧毁",
    finalScore: "最终得分",
    levelReached: "到达关卡",
    enemiesSlain: "击杀敌机",
    achievements: "成就系统",
    tryAgain: "再次尝试",
    mainMenu: "主菜单",
    missionIntel: "任务情报",
    enemyClasses: "敌机类型",
    tacticalInfo: "战术指南",
    striker: "突击者",
    strikerDesc: "标准侦察机",
    interceptor: "拦截者",
    interceptorDesc: "高速度，低生命值",
    dreadnought: "无畏舰",
    dreadnoughtDesc: "重型装甲，高生命值",
    tactical1: "敌机逃脱将扣除50分。",
    tactical2: "关卡升级将清除当前区域所有敌机。",
    tactical3: "能量护盾可抵挡一次碰撞伤害。",
    tactical4: "三向子弹持续时间为10秒。",
    controls: "操作指南",
    powerups: "道具系统",
    move: "移动",
    shoot: "射击",
    pause: "暂停",
    mobile: "移动端",
    tripleShot: "三向子弹",
    shield: "能量护盾",
    repair: "紧急维修",
    repairDesc: "恢复1点生命值 (上限3)",
    highScore: "最高分",
    level: "关卡",
    achievementUnlocked: "解锁成就！",
    gameplayIntro: "驾驶你的星际战机穿梭于敌阵之中。摧毁来袭威胁，收集强力道具，尽可能久地生存下去以获得最高分。",
    howToPlay: "游戏玩法",
    achievementList: "成就挑战",
    tripleShotDesc: "同时发射三枚子弹",
    shieldDesc: "抵挡一次碰撞伤害",
    powerupClasses: "道具类型",
    achievements_data: {
      first_blood: { title: "第一滴血", desc: "摧毁你的第一架敌机。" },
      survivor: { title: "幸存者", desc: "到达第5关。" },
      ace_pilot: { title: "王牌飞行员", desc: "获得10,000分。" },
      power_hungry: { title: "道具狂人", desc: "单局收集5个道具。" },
      untouchable: { title: "不可触碰", desc: "在不损失生命的情况下摧毁50架敌机。" }
    }
  }
};
